/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jgame.gradle;

import org.junit.jupiter.api.Test;

import jgame.Main;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        new Main();
        //App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
